[versions]
spring-boot = "4.1.1"
spring-dependency-management = "1.1.7"
java = "25"
maven-publish = "0.37.0"
jjwt = "0.13.0"
caffeine = "3.2.4"
checker-qual = "4.2.1"

[libraries]
# BOM
spring-boot-dependencies = { module = "org.springframework.boot:spring-boot-dependencies", version.ref = "spring-boot" }

# Production Dependencies
spring-boot-starter-security = { module = "org.springframework.boot:spring-boot-starter-security" }
spring-boot-starter-web = { module = "org.springframework.boot:spring-boot-starter-web" }
spring-boot-starter-validation = { module = "org.springframework.boot:spring-boot-starter-validation" }
spring-boot-starter-data-redis = { module = "org.springframework.boot:spring-boot-starter-data-redis" }
spring-boot-autoconfigure = { module = "org.springframework.boot:spring-boot-autoconfigure" }
spring-boot-configuration-processor = { module = "org.springframework.boot:spring-boot-configuration-processor" }
spring-security-core = { module = "org.springframework.security:spring-security-core" }
spring-security-web = { module = "org.springframework.security:spring-security-web" }
spring-security-config = { module = "org.springframework.security:spring-security-config" }
spring-security-oauth2-jose = { module = "org.springframework.security:spring-security-oauth2-jose" }
jjwt-api = { module = "io.jsonwebtoken:jjwt-api", version.ref = "jjwt" }
jjwt-impl = { module = "io.jsonwebtoken:jjwt-impl", version.ref = "jjwt" }
jjwt-jackson = { module = "io.jsonwebtoken:jjwt-jackson", version.ref = "jjwt" }
caffeine = { module = "com.github.ben-manes.caffeine:caffeine", version.ref = "caffeine" }
checker-qual = { module = "org.checkerframework:checker-qual", version.ref = "checker-qual" }

# Test Dependencies
spring-test = { module = "org.springframework:spring-test" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter" }
assertj-core = { module = "org.assertj:assertj-core" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }

[plugins]
spring-dependency-management = { id = "io.spring.dependency-management", version.ref = "spring-dependency-management" }
maven-publish-plugin = { id = "com.vanniktech.maven.publish", version.ref = "maven-publish" }
